name: TruffleHog Secrets Scan

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@092db2aa9d836cdc0bb2c9fcc93435d026e14d0c # v-latest from @main
        continue-on-error: true
        with:
          path: ./
          base_depth: 1
          debug: true
